# Generated by Django 2.2 on 2020-06-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked_by',
        ),
    ]
