# Generated by Django 2.2 on 2020-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_remove_book_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_books', to='book_app.User'),
        ),
    ]
